### ISSUE TITLE
i18n not working, cannot get it to work

### ISSUE THREAD

**Issue by princemaple** [princemaple/weather_app#1]
both 
- `{{t "blah"}}`

and
- `this.I18n.t("blah")`

are not working.

**Comment by jwswj** [comment]
@princemaple do you have a branch where you were trying to get this to work? Open up a Pull Request on the repo and I'll help debug why.

**Comment by princemaple** [comment]
@jwswj https://github.com/princemaple/weather_app/pull/4

I had a branch called "fresh", it was used to identifying bugs, where I deleted most of the code then progressively added chunks of code back. It got merged back into master after I identified the bug.

I opened up this new branch called "debug" and added one new commit to reveal the bug.

**Comment by jwswj** [comment]
Can you submit a pull request for this branch?

**Comment by princemaple** [comment]
Errm, I did. #4.

Regards,

Po Chen

[sent from mobile phone]

**Comment by jwswj** [comment]
My bad. Will have a look

**Comment by princemaple** [comment]
Thanks.

**Comment by princemaple** [comment]
Reason stated in #4 
closing.
